monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.usb-AlphaTheta_Corporation_DDJ-FLX4.*" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
